benchmarks:
  - name: crc_32
    scale_factor: 6
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096

        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096

  - name: huffbench
    scale_factor: 1
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096

        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: matmult-int
    scale_factor: 1
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
      - name: micro-bpf
        env:
          RIOT_STACK: 4096
          ENABLE_JIT: 0

      - name: wamr
        env:
          RIOT_STACK: 4096
          STACK: 4096


      - name: wamr
        label: wamr-fast
        env:
          INTERPRETER: FAST
          RIOT_STACK: 4096
          STACK: 4096


  - name: md5
    scale_factor: 2
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: mont64
    scale_factor: 13
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: nettle-sha256
    scale_factor: 12
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: nsichneu
    scale_factor: 20
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: slre
    scale_factor: 2
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096

        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: statemate
    scale_factor: 86
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096

        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096

  - name: tarfind
    scale_factor: 3
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: ud
    scale_factor: 41
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096


  - name: xgboost
    scale_factor: 1
    iterations: 32
    boards:
    - board_name: nrf52840dk
      supported_environments:
        - name: micro-bpf
          env:
            RIOT_STACK: 4096
            ENABLE_JIT: 0

        - name: wamr
          env:
            RIOT_STACK: 4096
            STACK: 4096


        - name: wamr
          label: wamr-fast
          env:
            INTERPRETER: FAST
            RIOT_STACK: 4096
            STACK: 4096

